CREATE TABLE PUBLIC.DONORS (
	DONOR_ID IDENTITY NOT NULL,
	CREATED_ON DATE,
	FIRST_NAME VARCHAR(255),
	LAST_NAME VARCHAR(255),
	TOWN VARCHAR(255),
	CONSTRAINT PK_DONORS PRIMARY KEY (DONOR_ID)
);

CREATE TABLE PUBLIC.DONATIONS (
	DONAT_ID IDENTITY NOT NULL,
	AMOUNT BIGINT,
	DATE_DT DATE,
	MESSAGE VARCHAR(255),
	DONOR_ID BIGINT,
	CREATED_ON DATE,
	CONSTRAINT PK_DONATIONS PRIMARY KEY (DONAT_ID)
);

ALTER TABLE PUBLIC.DONATIONS ADD CONSTRAINT FK_DONOR FOREIGN KEY (DONOR_ID) REFERENCES PUBLIC.DONORS(DONOR_ID);